name: Build, Test and Deploy Coverage Report

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'

    - name: Install ReportGenerator
      run: dotnet tool install -g dotnet-reportgenerator-globaltool

    - name: Install dependencies
      run: dotnet restore

    - name: Run tests and collect coverage
      run: |
        dotnet test --settings tests.runsettings

    - name: Find latest coverage report
      id: find-coverage
      run: |
        # Find the latest coverage report file path
        COVERAGE_FILE=$(find $(pwd)/ChatSupport.Tests/TestResults -name "coverage.cobertura.xml" | sort | tail -n 1)
        echo "Coverage report path: $COVERAGE_FILE"
        echo "coverage-file=$COVERAGE_FILE" >> $GITHUB_ENV

    - name: Generate coverage report
      run: |
        reportgenerator -reports:${{ env.coverage-file }} -targetdir:coverage -reporttypes:Html

    - name: Setup Pages
      if: github.ref == 'refs/heads/master'
      uses: actions/configure-pages@v3

    - name: Upload Artifact
      if: github.ref == 'refs/heads/master'
      uses: actions/upload-pages-artifact@v1
      with:
        path: "./coverage"
        
  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: build
    
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
